/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
__int64 sub_400B70();
// char *getenv(const char *name);
// int strcasecmp(const char *s1, const char *s2);
// int *__errno_location(void);
// char *strcpy(char *dest, const char *src);
// int puts(const char *s);
// ssize_t write(int fd, const void *buf, size_t n);
// unsigned int alarm(unsigned int seconds);
// int close(int fd);
// ssize_t read(int fd, void *buf, size_t nbytes);
// char *fgets(char *s, int n, FILE *stream);
// __sighandler_t signal(int sig, __sighandler_t handler);
// struct hostent *gethostbyname(const char *name);
// __int64 __fastcall __memmove_chk(_QWORD, _QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall __memcpy_chk(_QWORD, _QWORD, _QWORD, _QWORD); weak
// __int64 __gmon_start__(void); weak
// __int64 strtol(const char *nptr, char **endptr, int base);
// int fflush(FILE *stream);
// __int64 __fastcall __isoc99_sscanf(__int64 a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5);
// __int64 __fastcall __printf_chk(_QWORD, _QWORD, _QWORD); weak
// FILE *fopen(const char *filename, const char *modes);
// int gethostname(char *name, size_t len);
// void __noreturn exit(int status);
// int connect(int fd, const struct sockaddr *addr, socklen_t len);
// __int64 __fastcall __fprintf_chk(_QWORD, _QWORD, _QWORD, _QWORD); weak
// unsigned int sleep(unsigned int seconds);
// const unsigned __int16 **__ctype_b_loc(void);
// __int64 __fastcall __sprintf_chk(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD); weak
// int socket(int domain, int type, int protocol);
signed __int64 deregister_tm_clones();
__int64 register_tm_clones();
signed __int64 _do_global_dtors_aux();
__int64 frame_dummy();
int __cdecl main(int argc, const char **argv, const char **envp);
__int64 __fastcall phase_1(_BYTE *a1);
__int64 __fastcall phase_2(__int64 a1);
__int64 __fastcall phase_3(__int64 a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5);
__int64 __fastcall func4(int a1, unsigned int a2);
__int64 __fastcall phase_4(__int64 a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5);
__int64 __fastcall phase_5(_BYTE *a1, __int64 a2);
__int64 __fastcall phase_6(__int64 a1);
signed __int64 __fastcall fun7(__int64 a1, int a2);
unsigned __int64 secret_phase();
void __noreturn sig_handler();
void __fastcall __noreturn invalid_phase(__int64 a1);
__int64 __fastcall string_length(_BYTE *a1);
__int64 __fastcall strings_not_equal(_BYTE *a1, _BYTE *a2);
unsigned __int64 initialize_bomb();
signed __int64 __fastcall blank_line(char *a1);
char *skip();
unsigned __int64 __fastcall send_msg(__int64 a1, __int64 a2, __int64 a3);
void __fastcall __noreturn explode_bomb(__int64 a1, __int64 a2);
__int64 __fastcall read_six_numbers(__int64 a1, __int64 a2);
const char *read_line();
unsigned __int64 __fastcall phase_defused(__int64 a1, __int64 a2, __int64 a3);
void __noreturn sigalrm_handler();
signed __int64 __fastcall rio_readlineb(__int64 a1, _BYTE *a2, unsigned __int64 a3);
// __int64 __usercall submitr@<rax>(char *name@<rdi>, _BYTE *a2@<rdx>, const char *a3@<rcx>, __int16 a4@<si>, _BYTE *a5@<r9>, __int64 a6, __int64 a7);
unsigned int __fastcall init_timeout(unsigned int seconds);
signed __int64 __fastcall init_driver(__int64 a1);
__int64 __fastcall driver_post(const char *a1, __int64 a2, __int64 a3, int a4, __int64 a5);
void __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3);
void term_proc();
// __int64 __fastcall _isoc99_sscanf(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD); weak

//-------------------------------------------------------------------------
// Data declarations

int array_3493[16] = { 2, 10, 6, 1, 12, 16, 9, 3, 4, 7, 14, 5, 11, 8, 15, 13 }; // idb
_UNKNOWN unk_4029C1; // weak
__int64 (__fastcall *_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
__int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
__int64 (*qword_604010)(void) = NULL; // weak
_UNKNOWN n1; // weak
_UNKNOWN node1; // weak
char user_password[21] = "N0YVLkjiKSpwvj6QrGK6"; // weak
char userid[12] = "16307130006"; // weak
int bomb_id = 75; // weak
char *host_table = "catlab-ubuntu"; // idb
_UNKNOWN unk_6043A8; // weak
FILE *_bss_start; // idb
__int64 stdin; // weak
__int64 stderr; // weak
char completed_6982; // weak
int num_input_strings; // weak
FILE *infile; // idb
__int64 input_strings[]; // weak
__int64 qword_6047E8[]; // weak
_UNKNOWN unk_6048D0; // weak
// extern _UNKNOWN _gmon_start__; weak


//----- (0000000000400B50) ----------------------------------------------------
void *init_proc()
{
  void *result; // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    result = (void *)__gmon_start__();
  return result;
}
// 400C80: using guessed type __int64 __gmon_start__(void);

//----- (0000000000400B70) ----------------------------------------------------
__int64 sub_400B70()
{
  return qword_604010();
}
// 604010: using guessed type __int64 (*qword_604010)(void);

//----- (0000000000400D60) ----------------------------------------------------
#error "400D66: positive sp value has been found (funcsize=3)"

//----- (0000000000400D90) ----------------------------------------------------
signed __int64 deregister_tm_clones()
{
  signed __int64 result; // rax

  result = 6309799LL - (_QWORD)&_bss_start;
  if ( (unsigned __int64)(6309799LL - (_QWORD)&_bss_start) > 0xE )
    result = 0LL;
  return result;
}

//----- (0000000000400DC0) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0LL;
}

//----- (0000000000400E00) ----------------------------------------------------
signed __int64 _do_global_dtors_aux()
{
  signed __int64 result; // rax

  if ( !completed_6982 )
  {
    result = deregister_tm_clones();
    completed_6982 = 1;
  }
  return result;
}
// 6047B8: using guessed type char completed_6982;

//----- (0000000000400E20) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 400E20: could not find valid save-restore pair for rbp

//----- (0000000000400E4D) ----------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  const char **v3; // rbx
  const char *v4; // rdi
  const char *v5; // rcx
  char *v6; // rdi
  __int64 v7; // rdx
  const char *v8; // rdi
  __int64 v9; // rdx
  const char *v10; // rdi
  __int64 v11; // rdx
  __int64 v12; // rcx
  __int64 v13; // r8
  __int64 v14; // rdx
  const char *v15; // rdi
  __int64 v16; // rdx
  __int64 v17; // rcx
  __int64 v18; // r8
  __int64 v19; // rdx
  char *v20; // rdi
  __int64 v21; // rdx
  const char *v22; // rdi
  __int64 v23; // rdx

  if ( argc == 1 )
  {
    infile = (FILE *)stdin;
  }
  else
  {
    v3 = argv;
    if ( argc != 2 )
    {
      __printf_chk(1LL, "Usage: %s [<input_file>]\n", *argv);
      exit(8);
    }
    v4 = argv[1];
    argv = (const char **)"r";
    infile = fopen(v4, "r");
    if ( !infile )
    {
      v5 = v3[1];
      __printf_chk(1LL, "%s: Error: Couldn't open %s\n", *v3);
      exit(8);
    }
  }
  initialize_bomb();
  puts("Welcome to my fiendish little bomb. You have 6 phases with");
  puts("which to blow yourself up. Have a nice day!");
  v6 = (char *)read_line();
  phase_1(v6);
  phase_defused((__int64)v6, (__int64)argv, v7);
  puts("Phase 1 defused. How about the next one?");
  v8 = read_line();
  phase_2((__int64)v8);
  phase_defused((__int64)v8, (__int64)argv, v9);
  puts("That's number 2.  Keep going!");
  v10 = read_line();
  phase_3((__int64)v10, (__int64)argv, v11, v12, v13);
  phase_defused((__int64)v10, (__int64)argv, v14);
  puts("Halfway there!");
  v15 = read_line();
  phase_4((__int64)v15, (__int64)argv, v16, v17, v18);
  phase_defused((__int64)v15, (__int64)argv, v19);
  puts("So you got that one.  Try this one.");
  v20 = (char *)read_line();
  phase_5(v20, (__int64)argv);
  phase_defused((__int64)v20, (__int64)argv, v21);
  puts("Good work!  On to the next...");
  v22 = read_line();
  phase_6((__int64)v22);
  phase_defused((__int64)v22, (__int64)argv, v23);
  return 0;
}
// 400CC0: using guessed type __int64 __fastcall __printf_chk(_QWORD, _QWORD, _QWORD);
// 6047A8: using guessed type __int64 stdin;

//----- (0000000000400F90) ----------------------------------------------------
__int64 __fastcall phase_1(_BYTE *a1)
{
  __int64 result; // rax

  result = strings_not_equal(a1, "For NASA, space is still a high priority.");
  if ( (_DWORD)result )
    explode_bomb((__int64)a1, (__int64)"For NASA, space is still a high priority.");
  return result;
}

//----- (0000000000400FAC) ----------------------------------------------------
__int64 __fastcall phase_2(__int64 a1)
{
  __int64 result; // rax
  signed int v2; // ebx
  char *v3; // rbp
  int v4; // [rsp+0h] [rbp-38h]
  char v5; // [rsp+4h] [rbp-34h]

  read_six_numbers(a1, (__int64)&v4);
  if ( v4 < 0 )
    explode_bomb(a1, (__int64)&v4);
  v3 = &v5;
  v2 = 1;
  do
  {
    result = (unsigned int)(*((_DWORD *)v3 - 1) + v2);
    if ( *(_DWORD *)v3 != (_DWORD)result )
      explode_bomb(a1, (__int64)&v4);
    ++v2;
    v3 += 4;
  }
  while ( v2 != 6 );
  return result;
}

//----- (0000000000400FF7) ----------------------------------------------------
__int64 __fastcall phase_3(__int64 a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5)
{
  signed int v5; // eax
  int v6; // eax
  int v7; // eax
  int v8; // eax
  int v9; // eax
  int v10; // eax
  int v11; // eax
  __int64 result; // rax
  int v13; // [rsp+8h] [rbp-10h]
  int v14; // [rsp+Ch] [rbp-Ch]

  if ( (signed int)__isoc99_sscanf(a1, (__int64)"%d %d", (__int64)&v13, (__int64)&v14, a5) <= 1 )
    explode_bomb(a1, (__int64)"%d %d");
  switch ( v13 )
  {
    case 0:
      v5 = 893;
      goto LABEL_6;
    case 1:
      v5 = 0;
LABEL_6:
      v6 = v5 - 253;
      goto LABEL_8;
    case 2:
      v6 = 0;
LABEL_8:
      v7 = v6 + 524;
      goto LABEL_10;
    case 3:
      v7 = 0;
LABEL_10:
      v8 = v7 - 412;
      goto LABEL_12;
    case 4:
      v8 = 0;
LABEL_12:
      v9 = v8 + 412;
      goto LABEL_14;
    case 5:
      v9 = 0;
LABEL_14:
      v10 = v9 - 412;
      goto LABEL_16;
    case 6:
      v10 = 0;
LABEL_16:
      v11 = v10 + 412;
      break;
    case 7:
      v11 = 0;
      break;
    default:
      explode_bomb(a1, (__int64)"%d %d");
      return result;
  }
  result = (unsigned int)(v11 - 412);
  if ( v13 > 5 || (_DWORD)result != v14 )
    explode_bomb(a1, (__int64)"%d %d");
  return result;
}

//----- (00000000004010AC) ----------------------------------------------------
__int64 __fastcall func4(int a1, unsigned int a2)
{
  __int64 result; // rax
  int v3; // er12

  if ( a1 <= 0 )
    return 0LL;
  result = a2;
  if ( a1 != 1 )
  {
    v3 = (unsigned __int64)func4(a1 - 1, a2) + a2;
    result = v3 + (unsigned int)func4(a1 - 2, a2);
  }
  return result;
}

//----- (00000000004010E4) ----------------------------------------------------
__int64 __fastcall phase_4(__int64 a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5)
{
  __int64 v5; // rsi
  __int64 result; // rax
  unsigned int v7; // [rsp+8h] [rbp-10h]
  int v8; // [rsp+Ch] [rbp-Ch]

  if ( (unsigned int)__isoc99_sscanf(a1, (__int64)"%d %d", (__int64)&v8, (__int64)&v7, a5) != 2 || v7 - 2 > 2 )
    explode_bomb(a1, (__int64)"%d %d");
  v5 = v7;
  result = func4(6, v7);
  if ( (_DWORD)result != v8 )
    explode_bomb(6LL, v5);
  return result;
}

//----- (0000000000401135) ----------------------------------------------------
__int64 __fastcall phase_5(_BYTE *a1, __int64 a2)
{
  __int64 result; // rax
  int v3; // edx

  if ( (unsigned int)string_length(a1) != 6 )
    explode_bomb((__int64)a1, a2);
  result = 0LL;
  v3 = 0;
  do
    v3 += array_3493[a1[result++] & 0xF];
  while ( result != 6 );
  if ( v3 != 55 )
    explode_bomb((__int64)a1, a2);
  return result;
}

//----- (0000000000401176) ----------------------------------------------------
__int64 __fastcall phase_6(__int64 a1)
{
  int *v1; // r13
  signed int v2; // er12
  signed int v3; // ebx
  char *v4; // rax
  unsigned __int64 v5; // rsi
  _QWORD *v6; // rdx
  signed int v7; // eax
  int v8; // ecx
  __int64 v9; // rbx
  char *v10; // rax
  __int64 i; // rcx
  __int64 v12; // rdx
  signed int v13; // ebp
  __int64 result; // rax
  int v15[6]; // [rsp+0h] [rbp-78h]
  char v16; // [rsp+18h] [rbp-60h]
  __int64 v17; // [rsp+20h] [rbp-58h]
  char v18; // [rsp+28h] [rbp-50h]
  char v19; // [rsp+50h] [rbp-28h]

  v1 = v15;
  read_six_numbers(a1, (__int64)v15);
  v2 = 0;
  while ( 1 )
  {
    if ( (unsigned int)(*v1 - 1) > 5 )
      explode_bomb(a1, (__int64)v15);
    if ( ++v2 == 6 )
      break;
    v3 = v2;
    do
    {
      if ( *v1 == v15[v3] )
        explode_bomb(a1, (__int64)v15);
      ++v3;
    }
    while ( v3 <= 5 );
    ++v1;
  }
  v4 = (char *)v15;
  do
  {
    *(_DWORD *)v4 = 7 - *(_DWORD *)v4;
    v4 += 4;
  }
  while ( v4 != &v16 );
  v5 = 0LL;
  do
  {
    v8 = v15[v5 / 4];
    if ( v8 <= 1 )
    {
      v6 = &node1;
    }
    else
    {
      v7 = 1;
      v6 = &node1;
      do
      {
        v6 = (_QWORD *)v6[1];
        ++v7;
      }
      while ( v7 != v8 );
    }
    *(__int64 *)((char *)&v17 + 2 * v5) = (__int64)v6;
    v5 += 4LL;
  }
  while ( v5 != 24 );
  v9 = v17;
  v10 = &v18;
  for ( i = v17; ; i = v12 )
  {
    v12 = *(_QWORD *)v10;
    *(_QWORD *)(i + 8) = *(_QWORD *)v10;
    v10 += 8;
    if ( v10 == &v19 )
      break;
  }
  *(_QWORD *)(v12 + 8) = 0LL;
  v13 = 5;
  do
  {
    result = **(unsigned int **)(v9 + 8);
    if ( *(_DWORD *)v9 < (signed int)result )
      explode_bomb(a1, (__int64)&v19);
    v9 = *(_QWORD *)(v9 + 8);
    --v13;
  }
  while ( v13 );
  return result;
}
// 401176: using guessed type int var_78[6];

//----- (0000000000401286) ----------------------------------------------------
signed __int64 __fastcall fun7(__int64 a1, int a2)
{
  signed __int64 result; // rax

  if ( !a1 )
    return 0xFFFFFFFFLL;
  if ( *(_DWORD *)a1 > a2 )
    return 2 * (unsigned int)fun7(*(_QWORD *)(a1 + 8), a2);
  result = 0LL;
  if ( *(_DWORD *)a1 != a2 )
    result = 2 * (unsigned int)fun7(*(_QWORD *)(a1 + 16), a2) + 1;
  return result;
}

//----- (00000000004012C4) ----------------------------------------------------
unsigned __int64 secret_phase()
{
  const char *v0; // rdi
  unsigned int v1; // ebx
  __int64 v2; // rdx

  v0 = read_line();
  v1 = strtol(v0, 0LL, 10);
  if ( v1 - 1 > 0x3E8 )
    explode_bomb((__int64)v0, 0LL);
  if ( (unsigned int)fun7((__int64)&n1, v1) != 5 )
    explode_bomb((__int64)&n1, v1);
  puts("Wow! You've defused the secret stage!");
  return phase_defused((__int64)"Wow! You've defused the secret stage!", v1, v2);
}

//----- (0000000000401320) ----------------------------------------------------
void __noreturn sig_handler()
{
  __int64 v0; // rdx

  puts("So you think you can stop the bomb with ctrl-c, do you?");
  sleep(3u);
  __printf_chk(1LL, "Well...", v0);
  fflush(_bss_start);
  sleep(1u);
  puts("OK. :-)");
  exit(16);
}
// 400CC0: using guessed type __int64 __fastcall __printf_chk(_QWORD, _QWORD, _QWORD);

//----- (0000000000401376) ----------------------------------------------------
void __fastcall __noreturn invalid_phase(__int64 a1)
{
  __printf_chk(1LL, "Invalid phase%s\n", a1);
  exit(8);
}
// 400CC0: using guessed type __int64 __fastcall __printf_chk(_QWORD, _QWORD, _QWORD);

//----- (000000000040139B) ----------------------------------------------------
__int64 __fastcall string_length(_BYTE *a1)
{
  _BYTE *v1; // rdx
  __int64 result; // rax

  if ( !*a1 )
    return 0LL;
  v1 = a1;
  do
    result = (unsigned int)((_DWORD)++v1 - (_DWORD)a1);
  while ( *v1 );
  return result;
}

//----- (00000000004013B8) ----------------------------------------------------
__int64 __fastcall strings_not_equal(_BYTE *a1, _BYTE *a2)
{
  _BYTE *v2; // rbx
  _BYTE *v3; // rbp
  int v4; // er12
  int v5; // eax
  unsigned int v6; // edx

  v2 = a1;
  v3 = a2;
  v4 = string_length(a1);
  v5 = string_length(a2);
  v6 = 1;
  if ( v4 == v5 )
  {
    if ( *a1 )
    {
      if ( *a1 == *a2 )
      {
        do
        {
          ++v2;
          ++v3;
          if ( !*v2 )
            return 0;
        }
        while ( *v2 == *v3 );
        v6 = 1;
      }
      else
      {
        v6 = 1;
      }
    }
    else
    {
      v6 = 0;
    }
  }
  return v6;
}

//----- (0000000000401422) ----------------------------------------------------
unsigned __int64 initialize_bomb()
{
  const char *v0; // rdi
  _QWORD *v1; // rbx
  __int64 v3; // [rsp+0h] [rbp-2058h]
  char v4; // [rsp+40h] [rbp-2018h]
  unsigned __int64 v5; // [rsp+2048h] [rbp-10h]

  v5 = __readfsqword(0x28u);
  signal(2, (__sighandler_t)sig_handler);
  if ( gethostname((char *)&v3, 0x40uLL) )
  {
    puts("Initialization error: Running on an illegal host [1]");
    exit(8);
  }
  v0 = host_table;
  v1 = &unk_6043A8;
  if ( !host_table )
  {
LABEL_11:
    puts("Initialization error: Running on an illegal host [2]");
    exit(8);
  }
  while ( strcasecmp(v0, (const char *)&v3) )
  {
    ++v1;
    v0 = (const char *)*(v1 - 1);
    if ( !v0 )
      goto LABEL_11;
  }
  if ( (signed int)init_driver((__int64)&v4) < 0 )
  {
    __printf_chk(1LL, "Initialization error:\n%s\n", &v4);
    exit(8);
  }
  return __readfsqword(0x28u) ^ v5;
}
// 400CC0: using guessed type __int64 __fastcall __printf_chk(_QWORD, _QWORD, _QWORD);

//----- (0000000000401507) ----------------------------------------------------
signed __int64 __fastcall blank_line(char *a1)
{
  char *v1; // rbx
  char v2; // bp

  v1 = a1;
  do
  {
    v2 = *v1;
    if ( !*v1 )
      return 1LL;
    ++v1;
  }
  while ( (*__ctype_b_loc())[v2] & 0x2000 );
  return 0LL;
}

//----- (0000000000401544) ----------------------------------------------------
char *skip()
{
  char *v0; // rax
  char *v1; // rbx

  do
  {
    v0 = fgets((char *)(80LL * num_input_strings + 6309856), 80, infile);
    v1 = v0;
  }
  while ( v0 && (unsigned int)blank_line(v0) );
  return v1;
}
// 6047BC: using guessed type int num_input_strings;

//----- (0000000000401585) ----------------------------------------------------
unsigned __int64 __fastcall send_msg(__int64 a1, __int64 a2, __int64 a3)
{
  char v4; // [rsp+10h] [rbp-4018h]
  char s; // [rsp+2010h] [rbp-2018h]
  unsigned __int64 v6; // [rsp+4018h] [rbp-10h]

  v6 = __readfsqword(0x28u);
  if ( strlen((const char *)(80LL * (num_input_strings - 1) + 6309856)) + 100 > 0x2000 )
  {
    __printf_chk(1LL, "ERROR: Input string is too large.", a3);
    exit(8);
  }
  __sprintf_chk(&v4, 1LL, 0x2000LL, "%d:%s:%d:%s", (unsigned int)bomb_id);
  if ( (signed int)driver_post(userid, (__int64)user_password, (__int64)&v4, 0, (__int64)&s) < 0 )
  {
    puts(&s);
    exit(0);
  }
  return __readfsqword(0x28u) ^ v6;
}
// 400CC0: using guessed type __int64 __fastcall __printf_chk(_QWORD, _QWORD, _QWORD);
// 400D40: using guessed type __int64 __fastcall __sprintf_chk(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);
// 604394: using guessed type int bomb_id;
// 6047BC: using guessed type int num_input_strings;

//----- (0000000000401691) ----------------------------------------------------
void __fastcall __noreturn explode_bomb(__int64 a1, __int64 a2)
{
  __int64 v2; // rdx

  puts("\nBOOM!!!");
  puts("The bomb has blown up.");
  send_msg(0LL, a2, v2);
  puts("Your instructor has been notified.");
  exit(8);
}

//----- (00000000004016C7) ----------------------------------------------------
__int64 __fastcall read_six_numbers(__int64 a1, __int64 a2)
{
  __int64 result; // rax

  result = __isoc99_sscanf(a1, (__int64)&unk_4029C1, a2, a2 + 4, a2 + 8);
  if ( (signed int)result <= 5 )
    explode_bomb(a1, (__int64)&unk_4029C1);
  return result;
}

//----- (0000000000401709) ----------------------------------------------------
const char *read_line()
{
  int v0; // edx
  const char *v1; // rsi
  unsigned __int64 v2; // kr08_8
  int v3; // eax
  signed __int64 v4; // rax

  if ( !skip() )
  {
    if ( infile == (FILE *)stdin )
    {
      puts("Error: Premature EOF on stdin");
      exit(8);
    }
    if ( getenv("GRADE_BOMB") )
      exit(0);
    infile = (FILE *)stdin;
    if ( !skip() )
    {
      puts("Error: Premature EOF on stdin");
      exit(0);
    }
  }
  v0 = num_input_strings;
  v1 = (const char *)(80LL * num_input_strings + 6309856);
  v2 = strlen(v1) + 1;
  if ( (signed int)v2 - 1 > 78 )
  {
    puts("Error: Input line too long");
    v3 = num_input_strings++;
    v4 = 10LL * v3;
    input_strings[v4] = 7164793191628679722LL;
    qword_6047E8[v4] = 11868310583211105LL;
    explode_bomb(11868310583211105LL, (__int64)v1);
  }
  *((_BYTE *)&input_strings[10 * num_input_strings] + (signed int)v2 - 2) = 0;
  num_input_strings = v0 + 1;
  return v1;
}
// 6047A8: using guessed type __int64 stdin;
// 6047BC: using guessed type int num_input_strings;
// 6047E0: using guessed type __int64 input_strings[];
// 6047E8: using guessed type __int64 qword_6047E8[];

//----- (000000000040182F) ----------------------------------------------------
unsigned __int64 __fastcall phase_defused(__int64 a1, __int64 a2, __int64 a3)
{
  char v4; // [rsp+8h] [rbp-70h]
  char v5; // [rsp+Ch] [rbp-6Ch]
  char v6; // [rsp+10h] [rbp-68h]
  unsigned __int64 v7; // [rsp+68h] [rbp-10h]

  v7 = __readfsqword(0x28u);
  send_msg(1LL, a2, a3);
  if ( num_input_strings == 6 )
  {
    if ( (unsigned int)__isoc99_sscanf(
                         (__int64)&unk_6048D0,
                         (__int64)"%d %d %s",
                         (__int64)&v4,
                         (__int64)&v5,
                         (__int64)&v6) == 3
      && !(unsigned int)strings_not_equal(&v6, "DrEvil") )
    {
      puts("Curses, you've found the secret phase!");
      puts("But finding it and solving it are quite different...");
      secret_phase();
    }
    puts("Congratulations! You've defused the bomb!");
    puts("Your instructor has been notified and will verify your solution.");
  }
  return __readfsqword(0x28u) ^ v7;
}
// 6047BC: using guessed type int num_input_strings;

//----- (00000000004018E0) ----------------------------------------------------
void __noreturn sigalrm_handler()
{
  __fprintf_chk(stderr, 1LL, "Program timed out after %d seconds\n", 0LL);
  exit(1);
}
// 400D10: using guessed type __int64 __fastcall __fprintf_chk(_QWORD, _QWORD, _QWORD, _QWORD);
// 6047B0: using guessed type __int64 stderr;

//----- (000000000040190E) ----------------------------------------------------
signed __int64 __fastcall rio_readlineb(__int64 a1, _BYTE *a2, unsigned __int64 a3)
{
  _BYTE *v3; // r14
  signed int v4; // er13
  void *v5; // r12
  int v6; // eax
  int v7; // ebp
  _BOOL4 v8; // ST0C_4
  __int64 v9; // ST10_8
  char v10; // al
  signed int v11; // eax
  signed __int64 result; // rax
  unsigned __int64 v13; // [rsp+18h] [rbp-50h]
  char v14; // [rsp+2Fh] [rbp-39h]

  v3 = a2;
  v13 = a3;
  if ( a3 <= 1 )
  {
    v4 = 1;
LABEL_20:
    *v3 = 0;
    result = v4;
  }
  else
  {
    v4 = 1;
    v5 = (void *)(a1 + 16);
    while ( 1 )
    {
      while ( 1 )
      {
        v7 = *(_DWORD *)(a1 + 4);
        if ( v7 > 0 )
          break;
        v6 = read(*(_DWORD *)a1, v5, 0x2000uLL);
        *(_DWORD *)(a1 + 4) = v6;
        if ( v6 >= 0 )
        {
          if ( !v6 )
          {
            v11 = v4;
            goto LABEL_15;
          }
          *(_QWORD *)(a1 + 8) = v5;
        }
        else if ( *__errno_location() != 4 )
        {
          return -1LL;
        }
      }
      v8 = v7 != 0;
      v9 = *(_QWORD *)(a1 + 8);
      __memcpy_chk(&v14, *(_QWORD *)(a1 + 8), v7 != 0, 1LL);
      *(_QWORD *)(a1 + 8) = v9 + (v7 != 0);
      *(_DWORD *)(a1 + 4) = v7 - v8;
      if ( v8 != 1 )
        break;
      ++v3;
      v10 = v14;
      *(v3 - 1) = v14;
      if ( v10 != 10 && ++v4 < v13 )
        continue;
      goto LABEL_20;
    }
    if ( v7 != 0 )
      return -1LL;
    v11 = v4;
LABEL_15:
    if ( v11 != 1 )
      goto LABEL_20;
    result = 0LL;
  }
  return result;
}
// 400C70: using guessed type __int64 __fastcall __memcpy_chk(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000401A2C) ----------------------------------------------------
__int64 __usercall submitr@<rax>(char *name@<rdi>, _BYTE *a2@<rdx>, const char *a3@<rcx>, __int16 a4@<si>, _BYTE *a5@<r9>, __int64 a6, __int64 a7)
{
  _BYTE *v7; // r15
  unsigned __int8 *v8; // rbx
  int v9; // er12
  __int64 result; // rax
  struct hostent *v11; // rax
  unsigned __int64 v12; // rsi
  _BYTE *v13; // rdi
  signed __int64 v14; // rcx
  bool v15; // zf
  signed __int64 v16; // r8
  unsigned __int64 v17; // r9
  _BYTE *v18; // rdi
  signed __int64 v19; // rcx
  unsigned __int64 v20; // kr08_8
  char *i; // rbp
  unsigned __int8 v22; // r8
  signed __int64 v23; // rax
  ssize_t v24; // rax
  char *v25; // rbp
  size_t v26; // rbx
  int v27; // eax
  int v28; // edx
  int v29; // eax
  unsigned __int64 v30; // kr10_8
  _BYTE *v31; // [rsp+18h] [rbp-A090h]
  const char *v32; // [rsp+20h] [rbp-A088h]
  unsigned int v33; // [rsp+3Ch] [rbp-A06Ch]
  struct sockaddr addr; // [rsp+40h] [rbp-A068h]
  char src; // [rsp+50h] [rbp-A058h]
  char v36; // [rsp+51h] [rbp-A057h]
  char v37; // [rsp+52h] [rbp-A056h]
  char v38; // [rsp+2050h] [rbp-8058h]
  char v39; // [rsp+4050h] [rbp-6058h]
  char v40; // [rsp+6050h] [rbp-4058h]
  int v41; // [rsp+8050h] [rbp-2058h]
  int v42; // [rsp+8054h] [rbp-2054h]
  char *v43; // [rsp+8058h] [rbp-2050h]
  char v44; // [rsp+8060h] [rbp-2048h]
  unsigned __int64 v45; // [rsp+A068h] [rbp-40h]

  v31 = a2;
  v32 = a3;
  v7 = a5;
  v8 = (unsigned __int8 *)a6;
  v45 = __readfsqword(0x28u);
  v33 = 0;
  v9 = socket(2, 1, 0);
  if ( v9 < 0 )
  {
    *(_QWORD *)a7 = 4836930262966366789LL;
    *(_QWORD *)(a7 + 8) = 7959303600887654764LL;
    *(_QWORD *)(a7 + 16) = 2337214414117954145LL;
    *(_QWORD *)(a7 + 24) = 8295742064141103715LL;
    *(_DWORD *)(a7 + 32) = 1701536623;
    *(_WORD *)(a7 + 36) = 116;
    return 0xFFFFFFFFLL;
  }
  v11 = gethostbyname(name);
  if ( !v11 )
  {
    *(_QWORD *)a7 = 4908987857004294725LL;
    *(_QWORD *)(a7 + 8) = 7959303596504273742LL;
    *(_QWORD *)(a7 + 16) = 2337214414117954145LL;
    *(_QWORD *)(a7 + 24) = 2334402189959849330LL;
    *(_QWORD *)(a7 + 32) = 6998719601038222707LL;
    *(_DWORD *)(a7 + 40) = 1701995620;
    *(_WORD *)(a7 + 44) = 29555;
    *(_BYTE *)(a7 + 46) = 0;
    close(v9);
    return 0xFFFFFFFFLL;
  }
  *(_QWORD *)&addr.sa_family = 0LL;
  *(_QWORD *)&addr.sa_data[6] = 0LL;
  addr.sa_family = 2;
  __memmove_chk(&addr.sa_data[2], *v11->h_addr_list, v11->h_length, 12LL);
  *(_WORD *)addr.sa_data = __ROR2__(a4, 8);
  if ( connect(v9, &addr, 0x10u) < 0 )
  {
    *(_QWORD *)a7 = 6133966955649069637LL;
    *(_QWORD *)(a7 + 8) = 8031079655490609518LL;
    *(_QWORD *)(a7 + 16) = 8386658456067597088LL;
    *(_QWORD *)(a7 + 24) = 2334386829831140384LL;
    *(_DWORD *)(a7 + 32) = 1987208563;
    *(_WORD *)(a7 + 36) = 29285;
    *(_BYTE *)(a7 + 38) = 0;
    close(v9);
    return 0xFFFFFFFFLL;
  }
  v12 = strlen((const char *)a6) + 1;
  v13 = v31;
  v14 = -1LL;
  do
  {
    if ( !v14 )
      break;
    v15 = *v13++ == 0;
    --v14;
  }
  while ( !v15 );
  v16 = v14;
  v17 = strlen(v32) + 1;
  v18 = v7;
  v19 = -1LL;
  do
  {
    if ( !v19 )
      break;
    v15 = *v18++ == 0;
    --v19;
  }
  while ( !v15 );
  if ( v17 - v16 - v19 + 3 * v12 - 3 + 123 > 0x2000 )
  {
    *(_QWORD *)a7 = 5917794173535285829LL;
    *(_QWORD *)(a7 + 8) = 8391086215129297765LL;
    *(_QWORD *)(a7 + 16) = 8029764343147948402LL;
    *(_QWORD *)(a7 + 24) = 2318902353117408288LL;
    *(_QWORD *)(a7 + 32) = 7310293708491157065LL;
    *(_QWORD *)(a7 + 40) = 5932447205327983392LL;
    *(_QWORD *)(a7 + 48) = 19796991806623071LL;
    close(v9);
    return 0xFFFFFFFFLL;
  }
  memset(&v38, 0, 0x2000uLL);
  v20 = strlen((const char *)a6) + 1;
  if ( (_DWORD)v20 != 1 )
  {
    for ( i = &v38; ; i = (char *)v23 )
    {
      v22 = *v8;
      if ( *v8 != 42
        && (unsigned __int8)(v22 - 45) > 1u
        && v22 != 95
        && (unsigned __int8)(v22 - 48) > 9u
        && (unsigned __int8)((v22 & 0xDF) - 65) > 0x19u )
      {
        if ( v22 == 32 )
        {
          v23 = (signed __int64)(i + 1);
          *i = 43;
        }
        else
        {
          if ( (unsigned __int8)(v22 - 32) > 0x5Fu && v22 != 9 )
          {
            *(_QWORD *)a7 = 5917794173535285829LL;
            *(_QWORD *)(a7 + 8) = 8391086215129297765LL;
            *(_QWORD *)(a7 + 16) = 7957688057412348274LL;
            *(_QWORD *)(a7 + 24) = 7953674097058734452LL;
            *(_QWORD *)(a7 + 32) = 7809636914145552672LL;
            *(_QWORD *)(a7 + 40) = 8246212367049977632LL;
            *(_QWORD *)(a7 + 48) = 2334391151659085417LL;
            *(_QWORD *)(a7 + 56) = 7310577365311121507LL;
            *(_WORD *)(a7 + 64) = 11890;
            *(_BYTE *)(a7 + 66) = 0;
            close(v9);
            return 0xFFFFFFFFLL;
          }
          __sprintf_chk(&v41, 1LL, 8LL, "%%%02X", v22);
          *(_WORD *)i = v41;
          v23 = (signed __int64)(i + 3);
          i[2] = BYTE2(v41);
        }
      }
      else
      {
        v23 = (signed __int64)(i + 1);
        *i = v22;
      }
      if ( ++v8 == (unsigned __int8 *)(a6 + (unsigned int)(v20 - 2) + 1) )
        break;
    }
  }
  __sprintf_chk(
    &src,
    1LL,
    0x2000LL,
    "GET /%s/submitr.pl/?userid=%s&userpwd=%s&lab=%s&result=%s&submit=submit HTTP/1.0\r\n\r\n",
    v31);
  v30 = strlen(&src) + 1;
  if ( v30 == 1 )
  {
LABEL_36:
    v41 = v9;
    v42 = 0;
    v43 = &v44;
    if ( rio_readlineb((__int64)&v41, &src, 0x2000uLL) > 0 )
    {
      __isoc99_sscanf((__int64)&src, (__int64)"%s %d %[a-zA-z ]", (__int64)&v39, (__int64)&v33, (__int64)&v40);
      if ( v33 == 200 )
      {
        while ( src != 13 || v36 != 10 || v37 )
        {
          if ( rio_readlineb((__int64)&v41, &src, 0x2000uLL) <= 0 )
          {
            *(_QWORD *)a7 = 4836930262966366789LL;
            *(_QWORD *)(a7 + 8) = 7959303600887654764LL;
            *(_QWORD *)(a7 + 16) = 2337214414117954145LL;
            *(_QWORD *)(a7 + 24) = 7018130082659132786LL;
            *(_QWORD *)(a7 + 32) = 8030593375116879204LL;
            *(_QWORD *)(a7 + 40) = 8243124926671954029LL;
            *(_BYTE *)(a7 + 48) = 0;
            close(v9);
            return 0xFFFFFFFFLL;
          }
        }
        if ( rio_readlineb((__int64)&v41, &src, 0x2000uLL) > 0 )
        {
          strcpy((char *)a7, &src);
          close(v9);
          v27 = *(unsigned __int8 *)a7;
          v28 = 79 - v27;
          if ( v27 == 79 )
          {
            v29 = *(unsigned __int8 *)(a7 + 1);
            v28 = 75 - v29;
            if ( v29 == 75 )
              v28 = -*(unsigned __int8 *)(a7 + 2);
          }
          result = (unsigned int)-(v28 != 0);
        }
        else
        {
          *(_QWORD *)a7 = 4836930262966366789LL;
          *(_QWORD *)(a7 + 8) = 7959303600887654764LL;
          *(_QWORD *)(a7 + 16) = 2337214414117954145LL;
          *(_QWORD *)(a7 + 24) = 7022364301937698162LL;
          *(_QWORD *)(a7 + 32) = 8319104456053716340LL;
          *(_QWORD *)(a7 + 40) = 7885647255504775009LL;
          *(_QWORD *)(a7 + 48) = 32199706744812320LL;
          close(v9);
          result = 0xFFFFFFFFLL;
        }
      }
      else
      {
        __sprintf_chk(a7, 1LL, -1LL, "Error: HTTP request failed with error %d: %s", v33);
        close(v9);
        result = 0xFFFFFFFFLL;
      }
    }
    else
    {
      *(_QWORD *)a7 = 4836930262966366789LL;
      *(_QWORD *)(a7 + 8) = 7959303600887654764LL;
      *(_QWORD *)(a7 + 16) = 2337214414117954145LL;
      *(_QWORD *)(a7 + 24) = 8244232882187494770LL;
      *(_QWORD *)(a7 + 32) = 7306071583668335731LL;
      *(_QWORD *)(a7 + 40) = 8295750839044546674LL;
      *(_DWORD *)(a7 + 48) = 1702261349;
      *(_WORD *)(a7 + 52) = 114;
      close(v9);
      result = 0xFFFFFFFFLL;
    }
  }
  else
  {
    v26 = v30 - 1;
    v25 = &src;
    do
    {
      v24 = write(v9, v25, v26);
      if ( v24 <= 0 )
      {
        if ( *__errno_location() != 4 )
          goto LABEL_35;
        v24 = 0LL;
      }
      v25 += v24;
      v26 -= v24;
    }
    while ( v26 );
    if ( (signed __int64)(v30 - 1) >= 0 )
      goto LABEL_36;
LABEL_35:
    *(_QWORD *)a7 = 4836930262966366789LL;
    *(_QWORD *)(a7 + 8) = 7959303600887654764LL;
    *(_QWORD *)(a7 + 16) = 2337214414117954145LL;
    *(_QWORD *)(a7 + 24) = 8031079655625290359LL;
    *(_QWORD *)(a7 + 32) = 8243121275949052960LL;
    *(_DWORD *)(a7 + 40) = 7497078;
    close(v9);
    result = 0xFFFFFFFFLL;
  }
  return result;
}
// 400C60: using guessed type __int64 __fastcall __memmove_chk(_QWORD, _QWORD, _QWORD, _QWORD);
// 400D40: using guessed type __int64 __fastcall __sprintf_chk(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000402230) ----------------------------------------------------
unsigned int __fastcall init_timeout(unsigned int seconds)
{
  signed int v1; // ebx
  unsigned int v2; // edi
  unsigned int result; // eax

  v1 = seconds;
  if ( seconds )
  {
    signal(14, (__sighandler_t)sigalrm_handler);
    v2 = 0;
    if ( v1 >= 0 )
      v2 = v1;
    result = alarm(v2);
  }
  return result;
}

//----- (0000000000402257) ----------------------------------------------------
signed __int64 __fastcall init_driver(__int64 a1)
{
  int v1; // ebx
  signed __int64 result; // rax
  struct hostent *v3; // rax
  __int64 v4; // [rsp+0h] [rbp-38h]
  __int64 v5; // [rsp+8h] [rbp-30h]
  unsigned __int64 v6; // [rsp+18h] [rbp-20h]

  v6 = __readfsqword(0x28u);
  signal(13, (__sighandler_t)1);
  signal(29, (__sighandler_t)1);
  signal(29, (__sighandler_t)1);
  v1 = socket(2, 1, 0);
  if ( v1 >= 0 )
  {
    v3 = gethostbyname("10.48.76.8");
    if ( v3 )
    {
      v4 = 0LL;
      v5 = 0LL;
      LOWORD(v4) = 2;
      __memmove_chk((char *)&v4 + 4, *v3->h_addr_list, v3->h_length, 12LL);
      WORD1(v4) = 28219;
      if ( connect(v1, (const struct sockaddr *)&v4, 0x10u) >= 0 )
      {
        close(v1);
        *(_WORD *)a1 = 19279;
        *(_BYTE *)(a1 + 2) = 0;
        result = 0LL;
      }
      else
      {
        __sprintf_chk(a1, 1LL, -1LL, "Error: Unable to connect to server %s", "10.48.76.8");
        close(v1);
        result = 0xFFFFFFFFLL;
      }
    }
    else
    {
      *(_QWORD *)a1 = 4908987857004294725LL;
      *(_QWORD *)(a1 + 8) = 7959303596504273742LL;
      *(_QWORD *)(a1 + 16) = 2337214414117954145LL;
      *(_QWORD *)(a1 + 24) = 2334402189959849330LL;
      *(_QWORD *)(a1 + 32) = 6998719601038222707LL;
      *(_DWORD *)(a1 + 40) = 1701995620;
      *(_WORD *)(a1 + 44) = 29555;
      *(_BYTE *)(a1 + 46) = 0;
      close(v1);
      result = 0xFFFFFFFFLL;
    }
  }
  else
  {
    *(_QWORD *)a1 = 4836930262966366789LL;
    *(_QWORD *)(a1 + 8) = 7959303600887654764LL;
    *(_QWORD *)(a1 + 16) = 2337214414117954145LL;
    *(_QWORD *)(a1 + 24) = 8295742064141103715LL;
    *(_DWORD *)(a1 + 32) = 1701536623;
    *(_WORD *)(a1 + 36) = 116;
    result = 0xFFFFFFFFLL;
  }
  return result;
}
// 400C60: using guessed type __int64 __fastcall __memmove_chk(_QWORD, _QWORD, _QWORD, _QWORD);
// 400D40: using guessed type __int64 __fastcall __sprintf_chk(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (000000000040242C) ----------------------------------------------------
__int64 __fastcall driver_post(const char *a1, __int64 a2, __int64 a3, int a4, __int64 a5)
{
  __int64 v5; // rbx
  __int64 result; // rax

  v5 = a5;
  if ( a4 )
  {
    __printf_chk(1LL, "\nAUTORESULT_STRING=%s\n", a3);
    *(_WORD *)v5 = 19279;
    *(_BYTE *)(v5 + 2) = 0;
    result = 0LL;
  }
  else if ( a1 && *a1 )
  {
    result = submitr("10.48.76.8", "csapp", a1, 15214, "f12", a3, a5);
  }
  else
  {
    *(_WORD *)a5 = 19279;
    *(_BYTE *)(a5 + 2) = 0;
    result = 0LL;
  }
  return result;
}
// 400CC0: using guessed type __int64 __fastcall __printf_chk(_QWORD, _QWORD, _QWORD);

//----- (00000000004024B0) ----------------------------------------------------
void __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3)
{
  __int64 v3; // r13
  __int64 v4; // rbx
  signed __int64 v5; // rbp

  v3 = a3;
  v4 = 0LL;
  v5 = &_do_global_dtors_aux_fini_array_entry - _frame_dummy_init_array_entry;
  init_proc();
  if ( v5 )
  {
    do
      ((void (__fastcall *)(_QWORD, __int64, __int64))_frame_dummy_init_array_entry[v4++])(a1, a2, v3);
    while ( v4 != v5 );
  }
}
// 603E10: using guessed type __int64 (__fastcall *_frame_dummy_init_array_entry[2])();
// 603E18: using guessed type __int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)();

//----- (0000000000402524) ----------------------------------------------------
void term_proc()
{
  ;
}

#error "There were 1 decompilation failure(s) on 37 function(s)"
